[vars]
tty_blue = "\\033[%sm;34"
tty_yellow="\\033[%sm;33"
tty_green = "\\033[%sm;32"
tty_red = "\\033[%sm;31"
tty_bold = "\\033[%sm;39"
tty_reset = "\\033[%sm;0"

[tasks.install]
description = "install dependencies, assuming homebrew"
run = "brew bundle --file Brewfile"

[tasks."dev-blog"]
description = "run Jekyll dev blog - https://saramic.github.io/sentinel-box/"
run = """
    pushd docs && \
        bundle && \
        bundle exec jekyll serve && \
        popd
"""

[tasks.build]
description = "build"
run = """
    pio run -e in_blink_mbed
"""

[tasks.upload]
description = "upload firmware using OpenOCD"
run = """
    openocd \
        -s /usr/local/share/openocd/scripts \
        -f interface/cmsis-dap.cfg \
        -f target/max3263x.cfg \
        -c "program .pio/build/in_blink_mbed/firmware.elf verify reset exit"
"""

[tasks."upload:in_blink_LPSDK"]
description = "upload blink in LPSDK firmware"
run = """
    openocd \
        -s /usr/local/share/openocd/scripts \
        -f interface/cmsis-dap.cfg \
        -f target/max3263x.cfg \
        -c 'program experiments/in_blink_LPSDK/build/in_blink_lpsdk.elf verify reset exit'
"""

[tasks."upload:in_blink_rust"]
description = "upload blink in rust firmware"
run = """
    openocd \
        -s /usr/local/share/openocd/scripts \
        -f interface/cmsis-dap.cfg \
        -f target/max3263x.cfg \
        -c 'program experiments/in_blink_rust/target/thumbv7em-none-eabihf/release/in_blink_rust verify reset exit'
"""

[tools]
ruby = "3.2.2"
python = "3.11"
