; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
src_dir = experiments

[env:in_blink_mbed]
platform = maxim32
board = max32630fthr
framework = mbed
build_src_filter = +<in_blink_mbed/*>

upload_protocol = custom
; note the upload as a custom protocol needs a full build
; use `mise run upload` instead
upload_command = openocd -s /opt/homebrew/bin/../share/openocd/scripts \
  -f interface/cmsis-dap.cfg \
  -f target/max3263x.cfg \
  -c 'program .pio/build/max32630fthr/firmware.elf verify reset exit'

debug_tool = cmsis-dap
